name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EM_VERSION: 2.0.31

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: patch endless sky
        run: make patch
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-${{ env.EM_VERSION }}
      - name: install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install ${{ env.EM_VERSION }}
          ./emsdk/emsdk activate ${{ env.EM_VERSION }}
      - name: patch emscripten
        run: |
          cp emscripten-patch-rawnodefs.diff emsdk/upstream/emscripten/
          cd emsdk/upstream/emscripten; patch -p1 < emscripten-patch-rawnodefs.diff

      - name: emcc --clear-cache for some reason
        run: |
          source emsdk/emsdk_env.sh
          emcc --clear-cache

      - name: Cache libjpegturbo
        id: cache-libjpegturbo
        uses: actions/cache@v2
        env:
          cache-name: cache-libjpegturbo
        with:
          path: |
            libjpeg-turbo-2.1.0/
            2.1.0.tar.gz
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.EM_VERSION }}
      - name: Cache build directory
        id: cache-build
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        with:
          path: build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.EM_VERSION }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Set non-legacy env to avoid warning"
        # https://github.com/emscripten-core/emsdk/issues/862
        run: |
          source emsdk/emsdk_env.sh
          echo "EM_NODE_JS=$EMSDK_NODE" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Install deps and build library
        run: |
          source emsdk/emsdk_env.sh
          npm ci  # this also runs a build (because that's a prepublish script)
      - run: npm test
      - run: npm pack

      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./endless-sky-bindings-*.tgz

  test:
    needs: [build]
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: test
        working-directory: ./tests
        shell: bash
        run: |
          npm install
          echo current directory is
          pwd
          echo before installing
          echo ls .
          ls
          echo ls ..
          ls ..
          npm install ../*.tgz
          echo .
          ls
          echo ./node_modules
          ls node_modules
          echo ./node_modules/endles-sky-bindings
          ls node_modules/endless-sky-bindings
          echo ./node_modules/endles-sky-bindings/dist/
          ls node_modules/endless-sky-bindings/dist/
          npm test
